- name: Create App Application Machine
  hosts: localhost
  environment:
    GCP_AUTH_KIND: "{{gcp_auth_kind}}"
    GCP_SERVICE_ACCOUNT_FILE: "{{ gcp_service_account_file }}"
    GCP_SCOPES: "{{gcp_scopes}}"

  tasks:
    # Create Compute Instance
    - name: Create/Delete instance
      gcp_compute_instance:
        name: "{{ machine_instance_name }}"
        machine_type: "{{ machine_type }}"
        disks:
          - auto_delete: true
            boot: true
            initialize_params:
                source_image: "projects/debian-cloud/global/images/family/debian-11"
                disk_size_gb: "{{ machine_disk_size }}"
        network_interfaces:
          - access_configs:
              - name: "External NAT"
                type: "ONE_TO_ONE_NAT"
        tags:
          items:
            - http-server
            - https-server
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project }}"
        state: "{{ cluster_state }}"
      register: instance

    - name: Wait for SSH to come up
      wait_for: host={{ instance.networkInterfaces[0].accessConfigs[0].natIP }} port=22 delay=10 timeout=120
      when: cluster_state == "present"

    - name: Add host to groupname
      add_host: hostname={{ instance.networkInterfaces[0].accessConfigs[0].natIP }} groupname=new_instances
      when: cluster_state == "present"
